name: CI

#on: [push]

# åœ¨mainåˆ†æ”¯å‘ç”Ÿpushäº‹ä»¶æ—¶è§¦å‘ã€‚
on:
  push:
    branches:
      - main

env: # è®¾ç½®çŽ¯å¢ƒå˜é‡
  TZ: Asia/Shanghai # æ—¶åŒºï¼ˆè®¾ç½®æ—¶åŒºå¯ä½¿é¡µé¢ä¸­çš„`æœ€è¿‘æ›´æ–°æ—¶é—´`ä½¿ç”¨æ—¶åŒºæ—¶é—´ï¼‰

jobs:
  build: # è‡ªå®šä¹‰åç§°
    runs-on: ubuntu-latest # è¿è¡Œåœ¨è™šæ‹ŸæœºçŽ¯å¢ƒubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout ðŸ›Žï¸ # æ­¥éª¤1
        uses: actions/checkout@v2.3.1 # ä½¿ç”¨çš„åŠ¨ä½œã€‚æ ¼å¼ï¼šuserName/repoNameã€‚ä½œç”¨ï¼šæ£€å‡ºä»“åº“ï¼ŒèŽ·å–æºç ã€‚ å®˜æ–¹actionsåº“ï¼šhttps://github.com/actions
      - name: Install Node.js ${{ matrix.node-version }} ðŸ”§ # æ­¥éª¤2
        uses: actions/setup-node@v1 # ä½œç”¨ï¼šå®‰è£…nodejs
        with:
          node-version: ${{ matrix.node-version }} # ç‰ˆæœ¬
      - name: Build and Deploy ðŸš€ # æ­¥éª¤3 ï¼ˆåªæäº¤åˆ°githubå¯ä»¥ä½¿ç”¨è¿™ä¸ªæ­¥éª¤ï¼‰
        uses: JamesIves/github-pages-deploy-action@4.0.0 # ä½œç”¨ï¼šå°†é¡¹ç›®æž„å»ºå’Œéƒ¨ç½²åˆ°githubã€‚ https://github.com/JamesIves/github-pages-deploy-action
        env: # è®¾ç½®çŽ¯å¢ƒå˜é‡
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKenç§å¯†å˜é‡
          BASE_BRANCH: main # è¦éƒ¨ç½²çš„æ–‡ä»¶å¤¹æ‰€åœ¨çš„åˆ†æ”¯.
          BRANCH: gh-pages # éƒ¨ç½²åˆ°çš„åˆ†æ”¯
          FOLDER: docs/.vuepress/dist # è¦éƒ¨ç½²çš„æ–‡ä»¶å¤¹.
          BUILD_SCRIPT: npm install && npm run build && cd docs/.vuepress/dist && echo 'blog.wenbin.org.cn' > CNAME && cd -
